### PR TITLE
Commented the code, changed the hybrid automatons for surface and wal…

### PR DESCRIPTION
**Pull request by cerdogan**
…l grasp, added/changed parameters

### CODE REVIEW

**Comment by clemense** [comment]
You deleted the "create_edge_grasp" method, why?
This will create a run-time fault.

**Comment by cerdogan** [comment]
Regarding comment above, the edge grasp option is temporarily removed with 0cef8dc43aaf8cb6a55eb23dc80d3f78c696ace1 before further testing.

**Comment by clemense** [comment]
But wouldn't it make more sense to do this temporary fixing in a branch until it's done and only then pull into master? Rather than deleting things "temporarily" in master?

**Review by JessyVision — APPROVED** [review]

**Comment by cerdogan** [comment]
@clemense I would rather make sure everything in the master works and is reliable. I have not had a chance to test the edge grasp and I will add it back once we do.

**Pull request merged**
